<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD 추가 -->
<!DOCTYPE memberList 
[
<!ELEMENT memberList (memberInfo+)>
<!ELEMENT memberInfo (name, telephone, curriculumn?, zipCode, addr)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT curriculumn (sub+)>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT zipCode (#PCDATA)>
<!ELEMENT addr (#PCDATA)>
<!ATTLIST memberInfo mid CDATA #IMPLIED>
]>

<!-- #IMPLIED : 이 속성은 명시되기도 하고, 명시되지 않기도 한다. -->
<!-- #REQUIRED : 이 속성은 반드시 명시되어야 한다. -->
<!-- #FIXED : 이 속성은 특정 값으로 고정되어 사용된다. -->


<memberList>
    <!-- 루트 엘리먼트는 하나 -->
    <!-- 루트 엘리먼트의 이름은 『~~~~.xml』 파일 이름과 동일한 이름 사용 -->
    <!-- 스스로(본인)의 정보를 표현할 수 있는 문서 작성 -->
    <!-- + 우리 팀원들 -->
    
    <!-- ※ 복수(다수)의 데이터를 표현하는 경우 중간에 적절한 부모 태그 지정 -->
    <!-- ※ 엘리먼트 하위에는 엘리먼트(또는 데이터)만 구성 -->
    <!-- ※ 특수문자가 포함된 데이터인 경우 『CDATA 섹션』으로 처리 -->
    <!--                                 → 『<![CDATA[내용&내용]]>』 -->
    
    <memberInfo mid="1">
        <name>김한국</name>
        <telephone>010-1231-4564</telephone>
        <curriculumn>
            <sub>JAVA SE</sub>
            <sub>ORACLE</sub>
            <sub><![CDATA[Servlet&JSP]]></sub>
        </curriculumn>
        <zipCode>10234</zipCode>
        <addr>서울 마포구 월드컵북로 150</addr>
    </memberInfo>
    <memberInfo mid="2">
        <name>이영희</name>
        <telephone>010-5678-6789</telephone>        
        <zipCode>10234</zipCode>
        <addr>서울 마포구 월드컵북로 150</addr>
    </memberInfo>
    
</memberList>